In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [2]:
df= pd.read_csv('Python_Credit_Risk_XTrain.csv')

In [3]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [5]:
from sklearn.impute import SimpleImputer

In [6]:
si= SimpleImputer(missing_values= np.nan, strategy= 'most_frequent')
df_imputed= pd.DataFrame(si.fit_transform(df))
df_imputed.columns= df.columns
df_imputed.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

  ApplicantIncome CoapplicantIncome LoanAmount Loan_Amount_Term  \
0            5849               0.0      120.0            360.0   
1            4583            1508.0      128.0            360.0   
2            3000               0.0       66.0            360.0   
3            2583            2358.0      120.0            360.0   
4            6000               0.0      141.0            360.0   

  Credit_History Property_Area Loan_Status  
0            1.0         Urban           Y  
1            1.0         Rural           N  
2            1.0         Urban           Y  
3            1.0         Urban           Y  
4            1.0         Urban           Y

In [7]:
df_imputed.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [8]:
df_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    object
 7   CoapplicantIncome  614 non-null    object
 8   LoanAmount         614 non-null    object
 9   Loan_Amount_Term   614 non-null    object
 10  Credit_History     614 non-null    object
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: object(13)
memory usage: 62.5+ KB


In [9]:
# Encoding is required
df_imputed= df_imputed.drop(['Loan_ID'], axis=1)

In [10]:
df_imputed.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [11]:
df_imputed['Gender'].value_counts()

Male      502
Female    112
Name: Gender, dtype: int64

In [12]:
df_imputed['Gender']= df_imputed['Gender'].astype('category')
df_imputed['Gender']= df_imputed['Gender'].cat.codes

df_imputed['Married']= df_imputed['Married'].astype('category')
df_imputed['Married']= df_imputed['Married'].cat.codes

df_imputed['Dependents']= df_imputed['Dependents'].astype('category')
df_imputed['Dependents']= df_imputed['Dependents'].cat.codes
df_imputed= pd.get_dummies(df_imputed, columns=['Dependents'])

df_imputed['Education']= df_imputed['Education'].astype('category')
df_imputed['Education']= df_imputed['Education'].cat.codes

df_imputed['Self_Employed']= df_imputed['Self_Employed'].astype('category')
df_imputed['Self_Employed']= df_imputed['Self_Employed'].cat.codes

df_imputed['ApplicantIncome']= df_imputed['ApplicantIncome'].astype('float')
df_imputed['CoapplicantIncome']= df_imputed['CoapplicantIncome'].astype('float')
df_imputed['LoanAmount']= df_imputed['LoanAmount'].astype('float')
df_imputed['Loan_Amount_Term']= df_imputed['Loan_Amount_Term'].astype('float')
df_imputed['Credit_History']= df_imputed['Credit_History'].astype('float')

df_imputed['Property_Area']= df_imputed['Property_Area'].astype('category')
df_imputed['Property_Area']= df_imputed['Property_Area'].cat.codes
df_imputed= pd.get_dummies(df_imputed, columns=['Property_Area'])

df_imputed['Loan_Status']= df_imputed['Loan_Status'].astype('category')
df_imputed['Loan_Status']= df_imputed['Loan_Status'].cat.codes

df_imputed.head()

Gender  Married  Education  Self_Employed  ApplicantIncome  \
0       1        0          0              0           5849.0   
1       1        1          0              0           4583.0   
2       1        1          0              1           3000.0   
3       1        1          1              0           2583.0   
4       1        0          0              0           6000.0   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       120.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Loan_Status  Dependents_0  Dependents_1  Dependents_2  Dependents_3  \
0            1             1             0             0             0   
1            0             0             1             0             0   
2            1             1             0             0             0   
3            1             1             0             0             0   
4            1             1             0             0             0   

   Property_Area_0  Property_Area_1  Property_Area_2  
0                0                0                1  
1                1                0                0  
2                0                0                1  
3                0                0                1  
4                0                0                1

In [13]:
df_imputed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             614 non-null    int8   
 1   Married            614 non-null    int8   
 2   Education          614 non-null    int8   
 3   Self_Employed      614 non-null    int8   
 4   ApplicantIncome    614 non-null    float64
 5   CoapplicantIncome  614 non-null    float64
 6   LoanAmount         614 non-null    float64
 7   Loan_Amount_Term   614 non-null    float64
 8   Credit_History     614 non-null    float64
 9   Loan_Status        614 non-null    int8   
 10  Dependents_0       614 non-null    uint8  
 11  Dependents_1       614 non-null    uint8  
 12  Dependents_2       614 non-null    uint8  
 13  Dependents_3       614 non-null    uint8  
 14  Property_Area_0    614 non-null    uint8  
 15  Property_Area_1    614 non-null    uint8  
 16  Property_Area_2    614 non

In [14]:
df_imputed= df_imputed.drop(['Dependents_0', 'Property_Area_0'], axis=1)
df_imputed.head()

Gender  Married  Education  Self_Employed  ApplicantIncome  \
0       1        0          0              0           5849.0   
1       1        1          0              0           4583.0   
2       1        1          0              1           3000.0   
3       1        1          1              0           2583.0   
4       1        0          0              0           6000.0   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       120.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Loan_Status  Dependents_1  Dependents_2  Dependents_3  Property_Area_1  \
0            1             0             0             0                0   
1            0             1             0             0                0   
2            1             0             0             0                0   
3            1             0             0             0                0   
4            1             0             0             0                0   

   Property_Area_2  
0                1  
1                0  
2                1  
3                1  
4                1

In [15]:
# Check imbalance 
df_imputed['Loan_Status'].value_counts()

1    422
0    192
Name: Loan_Status, dtype: int64

This is imbalance dataset.

In [46]:
# Feature scaling
"""
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
x= scaler.fit_transform(x)
y= scaler.fit_transform(y)
"""

'\nfrom sklearn.preprocessing import StandardScaler\nscaler= StandardScaler()\nx= scaler.fit_transform(x)\ny= scaler.fit_transform(y)\n'

In [17]:
from imblearn.over_sampling import RandomOverSampler
over_sample= RandomOverSampler()
x_over, y_over= over_sample.fit_resample(x, y)

In [18]:
x.shape

(614, 14)

In [19]:
y.shape

(614,)

In [20]:
x_over.shape

(844, 14)

In [21]:
y_over.shape

(844,)

In [22]:
# Split data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x_over, y_over, random_state=1)

## Naive Bayes

In [23]:
from sklearn.naive_bayes import GaussianNB
gnb= GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [28]:
y_pred_train_gnb= gnb.predict(x_train)
y_pred_test_gnb= gnb.predict(x_test)

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(classification_report(y_train, y_pred_train_gnb))
print('..........................................')
print(classification_report(y_test, y_pred_test_gnb))
print('..........................................')
print(confusion_matrix(y_train, y_pred_train_gnb))
print('..........................................')
print(confusion_matrix(y_test, y_pred_test_gnb))
print('..........................................')
print(accuracy_score(y_train, y_pred_train_gnb))
print('..........................................')
print(accuracy_score(y_test, y_pred_test_gnb))

              precision    recall  f1-score   support

           0       0.91      0.52      0.66       308
           1       0.68      0.95      0.79       325

    accuracy                           0.74       633
   macro avg       0.79      0.74      0.73       633
weighted avg       0.79      0.74      0.73       633

..........................................
              precision    recall  f1-score   support

           0       0.86      0.44      0.58       114
           1       0.58      0.92      0.71        97

    accuracy                           0.66       211
   macro avg       0.72      0.68      0.65       211
weighted avg       0.73      0.66      0.64       211

..........................................
[[160 148]
 [ 16 309]]
..........................................
[[50 64]
 [ 8 89]]
..........................................
0.740916271721959
..........................................
0.6587677725118484


In [31]:
from sklearn.model_selection import cross_val_score
training_accuracy= cross_val_score(gnb, x_train, y_train, cv=10)
test_accuracy= cross_val_score(gnb, x_test, y_test, cv=10)
print(training_accuracy)
print('..................')
print(test_accuracy)

[0.640625   0.71875    0.796875   0.68253968 0.6984127  0.73015873
 0.68253968 0.6984127  0.74603175 0.76190476]
..................
[0.81818182 0.57142857 0.57142857 0.57142857 0.71428571 0.71428571
 0.52380952 0.80952381 0.76190476 0.66666667]


## SVM

Kernel- Linear/ Sigmoid, Polynomial, RBF

In [33]:
from sklearn.svm import SVC
svm_rbf= SVC(kernel= 'rbf')
svm_rbf.fit(x_train, y_train)

SVC()

In [34]:
y_pred_train_svm_rbf= svm_rbf.predict(x_train)
y_pred_test_svm_rbf= svm_rbf.predict(x_test)

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(classification_report(y_train, y_pred_train_svm_rbf))
print('..........................................')
print(classification_report(y_test, y_pred_test_svm_rbf))
print('..........................................')
print(confusion_matrix(y_train, y_pred_train_svm_rbf))
print('..........................................')
print(confusion_matrix(y_test, y_pred_test_svm_rbf))
print('..........................................')
print(accuracy_score(y_train, y_pred_train_svm_rbf))
print('..........................................')
print(accuracy_score(y_test, y_pred_test_svm_rbf))

              precision    recall  f1-score   support

           0       0.62      0.21      0.31       308
           1       0.54      0.88      0.67       325

    accuracy                           0.55       633
   macro avg       0.58      0.54      0.49       633
weighted avg       0.58      0.55      0.50       633

..........................................
              precision    recall  f1-score   support

           0       0.58      0.19      0.29       114
           1       0.47      0.84      0.60        97

    accuracy                           0.49       211
   macro avg       0.52      0.51      0.44       211
weighted avg       0.53      0.49      0.43       211

..........................................
[[ 65 243]
 [ 40 285]]
..........................................
[[22 92]
 [16 81]]
..........................................
0.5529225908372828
..........................................
0.4881516587677725


In [35]:
from sklearn.model_selection import cross_val_score
training_accuracy= cross_val_score(svm_rbf, x_train, y_train, cv=10)
test_accuracy= cross_val_score(svm_rbf, x_test, y_test, cv=10)
print(training_accuracy)
print('..................')
print(test_accuracy)

[0.484375   0.578125   0.546875   0.50793651 0.49206349 0.50793651
 0.53968254 0.50793651 0.52380952 0.49206349]
..................
[0.54545455 0.52380952 0.52380952 0.52380952 0.52380952 0.52380952
 0.52380952 0.57142857 0.47619048 0.57142857]


For C=10:

In [40]:
from sklearn.svm import SVC
svm_rbf_5= SVC(C=5, kernel= 'rbf')
svm_rbf_5.fit(x_train, y_train)

SVC(C=5)

In [41]:
y_pred_train_svm_rbf_5= svm_rbf_5.predict(x_train)
y_pred_test_svm_rbf_5= svm_rbf_5.predict(x_test)

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(classification_report(y_train, y_pred_train_svm_rbf_5))
print('..........................................')
print(classification_report(y_test, y_pred_test_svm_rbf_5))
print('..........................................')
print(confusion_matrix(y_train, y_pred_train_svm_rbf_5))
print('..........................................')
print(confusion_matrix(y_test, y_pred_test_svm_rbf_5))
print('..........................................')
print(accuracy_score(y_train, y_pred_train_svm_rbf_5))
print('..........................................')
print(accuracy_score(y_test, y_pred_test_svm_rbf_5))

              precision    recall  f1-score   support

           0       0.57      0.42      0.48       308
           1       0.56      0.70      0.62       325

    accuracy                           0.56       633
   macro avg       0.56      0.56      0.55       633
weighted avg       0.56      0.56      0.55       633

..........................................
              precision    recall  f1-score   support

           0       0.55      0.41      0.47       114
           1       0.47      0.61      0.53        97

    accuracy                           0.50       211
   macro avg       0.51      0.51      0.50       211
weighted avg       0.51      0.50      0.50       211

..........................................
[[128 180]
 [ 97 228]]
..........................................
[[47 67]
 [38 59]]
..........................................
0.5624012638230648
..........................................
0.5023696682464455
